# Generated by Django 2.2 on 2019-05-02 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location_city', models.CharField(max_length=50)),
                ('location_country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_role', models.CharField(max_length=100)),
                ('company_location', models.CharField(max_length=100)),
                ('Years_worked', models.IntegerField(default=0)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=200)),
                ('institute_location', models.CharField(max_length=200)),
                ('start_year', models.IntegerField(default=0)),
                ('end_year', models.IntegerField(default=0)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Candidate')),
            ],
        ),
    ]
