# Generated by Django 2.2.1 on 2019-05-02 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='job_role',
        ),
    ]
